#!/usr/bin/env bash

MACOS=false
LINUX=false
WIN=false

case "$(uname -s)" in
    Darwin                      ) MACOS=true;;
    Linux                       ) LINUX=true;;
    CYGWIN* | MINGW32* | MSYS*  ) WIN=true;;
    *                           ) echo "unknown OS"; exit 1;;
esac

# Check dependencies
if [[ "$MACOS" == true ]]; then
    if ! which brew > /dev/null 2>&1; then
        echo "You do not seem to have brew installed."
        echo "Please run:"
        echo -e "\n\truby -e \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"\n"
        echo "and try again."
        exit 1
    fi
    if ! brew ls --versions coreutils > /dev/null 2>&1; then
        echo "You do not seem to have coreutils installed."
        echo -e "Please run:\n\n\tbrew install coreutils\n\nand try again."
        exit 1
    fi
elif [[ "$LINUX" == true ]]; then
    if ! which apt-get > /dev/null 2>&1; then
        echo "You do not seem to have apt-get installed."
        # TODO update for yum
        exit 1
    fi
fi


if ! which pip > /dev/null 2>&1; then
    echo "You do not seem to have pip installed."
    if [[ "$MACOS" == true ]]; then
        echo -e "Please run:\n\n\tbrew install python\n\nand try again."
    elif [[ "$LINUX" == true ]]; then
        echo -e "Please run:\n\n\tsudo apt-get install python\n\nand try again."
    fi
    exit 1
fi

if ! which npm > /dev/null 2>&1; then
    if [[ "$MACOS" == true ]]; then
        brew install node
    elif [[ "$LINUX" == true ]]; then
        curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
        sudo apt-get install -y nodejs
    fi
fi

# link executables
for f in bin/*; do
    ln -is $PWD/$f /usr/local/bin/$(echo "$f" | sed 's#^.*/##g')
done
